import { describe, expect, it } from "vitest";
import { seedRows, seedSql } from "@/db/seed-rows";
import { CATALOG } from "../helpers/catalog";

describe("catalog seed rows", () => {
  const rows = seedRows(CATALOG);

  it("produces the documented counts with ordinals and an inactive version row", () => {
    expect(rows.version).toEqual({ id: CATALOG.versionId, source_snapshot: CATALOG.snapshot, is_active: false });
    expect(rows.locations).toHaveLength(46);
    expect(rows.locations.filter((location) => location.active_rank !== null)).toHaveLength(11);
    expect(rows.modifiers).toHaveLength(7);
    expect(rows.items).toHaveLength(506);
    expect(rows.items.map((item) => item.ordinal)).toEqual(rows.items.map((_, index) => index + 1));
    expect(rows.previews).toHaveLength(50);
    const byLocation = new Map<string, number[]>();
    for (const preview of rows.previews) byLocation.set(preview.location_id, [...(byLocation.get(preview.location_id) ?? []), preview.ordinal]);
    for (const ordinals of byLocation.values()) expect(ordinals).toEqual(ordinals.map((_, index) => index + 1));
  });

  it("emits idempotent SQL in one transaction that activates the version last", () => {
    const sql = seedSql(CATALOG);
    expect(sql.startsWith("-- Generated by scripts/seed-catalog.ts")).toBe(true);
    expect(sql).toContain("\nbegin;\n");
    expect(sql.trim().endsWith("commit;")).toBe(true);
    expect((sql.match(/on conflict do nothing;/g) ?? []).length).toBe(5);
    expect(sql).toContain("'Stack''d Underground'");
    expect(sql).toContain("array['no_onions', 'double', 'extra_cheese', 'no_lettuce', 'no_mayo']::text[]");
    expect(sql).toContain("'{}'::text[]");
    expect(sql.indexOf("set is_active = false")).toBeLessThan(sql.indexOf("set is_active = true"));
    expect(sql).not.toContain("sb_secret");
  });
});
