// Pure row builders for the catalog seed: Catalog value in, database rows and
// idempotent SQL out. No network, no environment. Used by scripts/seed-catalog.ts
// and its tests.
import type { Catalog } from "@/contracts";

export type SeedRows = {
  readonly version: { id: string; source_snapshot: Catalog["snapshot"]; is_active: false };
  readonly locations: readonly {
    version_id: string; id: string; name: string; location: string; menu_url: string | null; directory_menu_url: string | null;
    detail_url: string | null; source_sha256: string | null; source_note: string | null; active_rank: number | null;
  }[];
  readonly modifiers: readonly { version_id: string; id: string; label: string; price_cents: number }[];
  readonly items: readonly {
    version_id: string; id: string; ordinal: number; location_id: string; label: string; category: string; description: string;
    price_cents: number; aliases: readonly string[]; allowed_modifiers: readonly string[]; source_page: number | null;
  }[];
  readonly previews: readonly {
    version_id: string; location_id: string; ordinal: number; label: string; description: string; price_cents: number | null;
    source_url: string | null; source_page: number | null; source_sha256: string | null;
  }[];
};

export function seedRows(catalog: Catalog): SeedRows {
  const version_id = catalog.versionId;
  const previewOrdinals = new Map<string, number>();
  return {
    version: { id: version_id, source_snapshot: catalog.snapshot, is_active: false },
    locations: catalog.locations.map((location) => ({
      version_id, id: location.id, name: location.name, location: location.location, menu_url: location.menuUrl,
      directory_menu_url: location.directoryMenuUrl, detail_url: location.detailUrl, source_sha256: location.sourceSha256,
      source_note: location.sourceNote, active_rank: location.activeRank,
    })),
    modifiers: catalog.modifiers.map((modifier) => ({ version_id, id: modifier.id, label: modifier.label, price_cents: modifier.priceCents })),
    items: catalog.items.map((item, index) => ({
      version_id, id: item.id, ordinal: index + 1, location_id: item.locationId, label: item.label, category: item.category,
      description: item.description, price_cents: item.priceCents, aliases: item.aliases, allowed_modifiers: item.allowedModifiers,
      source_page: item.sourcePage,
    })),
    previews: catalog.previews.map((preview) => {
      const ordinal = (previewOrdinals.get(preview.locationId) ?? 0) + 1;
      previewOrdinals.set(preview.locationId, ordinal);
      return {
        version_id, location_id: preview.locationId, ordinal, label: preview.label, description: preview.description,
        price_cents: preview.priceCents, source_url: preview.sourceUrl, source_page: preview.sourcePage, source_sha256: preview.sourceSha256,
      };
    }),
  };
}

type Literal = string | number | boolean | null | readonly string[] | object;

function literal(value: Literal): string {
  if (value === null) return "null";
  if (typeof value === "number") return Number.isInteger(value) ? String(value) : (() => { throw new Error("Seed numbers must be integers."); })();
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  if (Array.isArray(value)) return value.length === 0 ? "'{}'::text[]" : `array[${value.map((entry) => literal(entry)).join(", ")}]::text[]`;
  return `${literal(JSON.stringify(value))}::jsonb`;
}

function insert(table: string, rows: readonly Record<string, Literal>[]): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const columns = Object.keys(rows[0]);
  const values = rows.map((row) => `  (${columns.map((column) => literal(row[column])).join(", ")})`).join(",\n");
  return `insert into public.${table} (${columns.join(", ")}) values\n${values}\non conflict do nothing;\n`;
}

/** Idempotent seed SQL: inserts skip existing rows, then the version is activated. */
export function seedSql(catalog: Catalog): string {
  const rows = seedRows(catalog);
  const version = literal(rows.version.id);
  return [
    `-- Generated by scripts/seed-catalog.ts from src/catalog/bundled.ts for version ${rows.version.id}.`,
    "-- Idempotent: every insert skips rows that already exist; catalog rows are never updated.",
    "begin;",
    insert("catalog_versions", [rows.version as unknown as Record<string, Literal>]),
    insert("locations", rows.locations as unknown as Record<string, Literal>[]),
    insert("modifiers", rows.modifiers as unknown as Record<string, Literal>[]),
    insert("items", rows.items as unknown as Record<string, Literal>[]),
    insert("menu_previews", rows.previews as unknown as Record<string, Literal>[]),
    `update public.catalog_versions set is_active = false where is_active and id <> ${version};`,
    `update public.catalog_versions set is_active = true where id = ${version};`,
    "commit;",
    "",
  ].join("\n");
}
