// Generated by the Supabase MCP generate_typescript_types for project rdjcqtpusbjxgigprpns
// on 2026-09-12 after migrations init_catalog_and_orders and items_ordinal. Advisory only:
// the shared Zod schemas in src/contracts remain the validation boundary.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_events: {
        Row: {
          code: string | null
          event: Json
          outcome: string
          recorded_at: string
          seq: number
          session_id: string
        }
        Insert: {
          code?: string | null
          event: Json
          outcome: string
          recorded_at?: string
          seq: number
          session_id: string
        }
        Update: {
          code?: string | null
          event?: Json
          outcome?: string
          recorded_at?: string
          seq?: number
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      catalog_versions: {
        Row: {
          id: string
          is_active: boolean
          published_at: string
          source_snapshot: Json
        }
        Insert: {
          id: string
          is_active?: boolean
          published_at?: string
          source_snapshot: Json
        }
        Update: {
          id?: string
          is_active?: boolean
          published_at?: string
          source_snapshot?: Json
        }
        Relationships: []
      }
      items: {
        Row: {
          aliases: string[]
          allowed_modifiers: string[]
          category: string
          description: string
          id: string
          label: string
          location_id: string
          ordinal: number
          price_cents: number
          source_page: number | null
          version_id: string
        }
        Insert: {
          aliases?: string[]
          allowed_modifiers?: string[]
          category: string
          description: string
          id: string
          label: string
          location_id: string
          ordinal: number
          price_cents: number
          source_page?: number | null
          version_id: string
        }
        Update: {
          aliases?: string[]
          allowed_modifiers?: string[]
          category?: string
          description?: string
          id?: string
          label?: string
          location_id?: string
          ordinal?: number
          price_cents?: number
          source_page?: number | null
          version_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "items_version_id_fkey"
            columns: ["version_id"]
            isOneToOne: false
            referencedRelation: "catalog_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_version_id_location_id_fkey"
            columns: ["version_id", "location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["version_id", "id"]
          },
        ]
      }
      locations: {
        Row: {
          active_rank: number | null
          detail_url: string | null
          directory_menu_url: string | null
          id: string
          location: string
          menu_url: string | null
          name: string
          source_note: string | null
          source_sha256: string | null
          version_id: string
        }
        Insert: {
          active_rank?: number | null
          detail_url?: string | null
          directory_menu_url?: string | null
          id: string
          location: string
          menu_url?: string | null
          name: string
          source_note?: string | null
          source_sha256?: string | null
          version_id: string
        }
        Update: {
          active_rank?: number | null
          detail_url?: string | null
          directory_menu_url?: string | null
          id?: string
          location?: string
          menu_url?: string | null
          name?: string
          source_note?: string | null
          source_sha256?: string | null
          version_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "locations_version_id_fkey"
            columns: ["version_id"]
            isOneToOne: false
            referencedRelation: "catalog_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      menu_previews: {
        Row: {
          description: string
          label: string
          location_id: string
          ordinal: number
          price_cents: number | null
          source_page: number | null
          source_sha256: string | null
          source_url: string | null
          version_id: string
        }
        Insert: {
          description: string
          label: string
          location_id: string
          ordinal: number
          price_cents?: number | null
          source_page?: number | null
          source_sha256?: string | null
          source_url?: string | null
          version_id: string
        }
        Update: {
          description?: string
          label?: string
          location_id?: string
          ordinal?: number
          price_cents?: number | null
          source_page?: number | null
          source_sha256?: string | null
          source_url?: string | null
          version_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "menu_previews_version_id_fkey"
            columns: ["version_id"]
            isOneToOne: false
            referencedRelation: "catalog_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "menu_previews_version_id_location_id_fkey"
            columns: ["version_id", "location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["version_id", "id"]
          },
        ]
      }
      modifiers: {
        Row: {
          id: string
          label: string
          price_cents: number
          version_id: string
        }
        Insert: {
          id: string
          label: string
          price_cents: number
          version_id: string
        }
        Update: {
          id?: string
          label?: string
          price_cents?: number
          version_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "modifiers_version_id_fkey"
            columns: ["version_id"]
            isOneToOne: false
            referencedRelation: "catalog_versions"
            referencedColumns: ["id"]
          },
        ]
      }
      receipts: {
        Row: {
          created_at: string
          id: string
          lines: Json
          review_id: string
          session_id: string
          total_cents: number
        }
        Insert: {
          created_at?: string
          id: string
          lines: Json
          review_id: string
          session_id: string
          total_cents: number
        }
        Update: {
          created_at?: string
          id?: string
          lines?: Json
          review_id?: string
          session_id?: string
          total_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "receipts_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      sessions: {
        Row: {
          allowed_location_ids: string[] | null
          catalog_version_id: string
          created_at: string
          id: string
          wait_config: Json | null
        }
        Insert: {
          allowed_location_ids?: string[] | null
          catalog_version_id: string
          created_at?: string
          id: string
          wait_config?: Json | null
        }
        Update: {
          allowed_location_ids?: string[] | null
          catalog_version_id?: string
          created_at?: string
          id?: string
          wait_config?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "sessions_catalog_version_id_fkey"
            columns: ["catalog_version_id"]
            isOneToOne: false
            referencedRelation: "catalog_versions"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
