/** UI language is independent of canonical menu IDs and integer-cent prices. */
export const LANGUAGES = [
  { id: 'en-US', name: 'English' },
  { id: 'es-ES', name: 'Español' },
  { id: 'zh-CN', name: '简体中文' },
] as const;
export type Language = typeof LANGUAGES[number]['id'];
const messages: Record<string, readonly [string,string]> = {
'Confirm simulated order ·':['Confirmar pedido simulado ·','确认模拟订单 ·'], 'item':['artículo','件'], 'items':['artículos','件'], 'of':['de','/'], 'Note for':['Nota para','备注：'],
"sample price":["precio de ejemplo", "示例价格"],
"published menu price":["precio publicado", "公布价格"],
"Preference:":["Preferencia:", "偏好："],
"Allergy:":["Alergia:", "过敏原："],
"Dislike:":["Evitar:", "忌口："],
"Keep":["Mantener", "保留"],
"Requested:":["Solicitado:", "已选："],
"Needs verification":["Requiere verificación", "需要核实"],
"Conflicts with requirements":["No cumple tus requisitos", "与要求冲突"],
"Matches recorded requirements":["Cumple los requisitos registrados", "符合已记录要求"],
"About this dietary evidence":["Acerca de la información alimentaria", "饮食信息说明"],
"Preference conflicts can request an explicit choice. Allergy conflicts and missing evidence cannot be overridden.":["Los conflictos de preferencia requieren una elección explícita. No se pueden ignorar conflictos de alergia ni información faltante.", "偏好冲突需要明确选择。过敏冲突或资料缺失不可绕过。"],
"No menu budget":["Sin presupuesto", "未设预算"],
"No menu budget set":["Sin presupuesto establecido", "未设菜单预算"],
"No limit":["Sin límite", "无限制"],
"Let the meal builder choose":["Elegir automáticamente", "自动选择餐品"],
"Remove exception":["Eliminar excepción", "移除例外"],
"Keep my current requirements":["Mantener mis requisitos", "保留当前要求"],
"Allow this exact preference exception":["Permitir esta excepción específica", "允许此特定偏好例外"],
"Leave meal mode; keep cart and profile":["Salir del modo comida; mantener pedido y preferencias", "退出套餐模式，保留订单和要求"],
"Clear cart and leave meal mode":["Vaciar pedido y salir del modo comida", "清空订单并退出套餐模式"],
"Peanuts":["Cacahuates", "花生"],
"Tree nuts":["Frutos secos de árbol", "树坚果"],
"Both":["Ambos", "两者"],
"Apply this change, erase it, or":["Aplica el cambio, bórralo o", "应用修改、清空输入或"],
"Discard this draft":["Descartar borrador", "放弃草稿"],
". A new review is required afterward.":[". Después debes revisar de nuevo.", "。之后需要重新核对订单。"],
"Show a summary to dining staff":["Mostrar resumen al personal", "向餐厅员工展示摘要"],
"Please verify these allergies:":["Verifica estas alergias:", "请核实以下过敏原："],
"Please check complete ingredients, preparation and cross-contact. No staff member has been contacted. This app cannot guarantee allergy safety or override missing evidence.":["Consulta los ingredientes completos, la preparación y el contacto cruzado. No se ha contactado al personal. Esta app no garantiza seguridad frente a alergias ni puede ignorar información faltante.", "请核实完整食材、制作过程和交叉接触。尚未联系员工。本应用无法保证过敏安全，也不能绕过缺失信息。"],
"Your requirements are held in this browser session. New order clears them. An explicit order-log download includes them; do not share that file unintentionally.":["Tus requisitos se guardan en esta sesión. Nuevo pedido los borra. La descarga del registro los incluye; compártela con cuidado.", "要求仅保存在本次浏览器会话。新订单会清除要求。下载的订单记录会包含这些信息，请谨慎分享。"],
"Menu prices only. Tax and fees are not included. You pay per item; this is not a meal-plan exchange.":["Solo precios del menú, sin impuestos ni cargos. Precio por artículo; no es un canje del plan de comidas.", "仅菜单价格，不含税费。按餐品计价，不是餐卡套餐兑换。"],
"Total uses listed menu prices. Counter prices, tax and meal-plan discounts may differ. Nothing will be sent to a dining location.":["El total usa los precios publicados. Los precios del local, impuestos y descuentos pueden variar. No se enviará nada al local.", "合计使用菜单标价。柜台价格、税费和餐卡折扣可能不同。不会发送至餐厅。"],
"Published or sample menu prices only; no tax or meal-plan discounts applied. Nothing was sent to a dining location.":["Solo precios publicados o de ejemplo; sin impuestos ni descuentos. No se envió nada al local.", "仅公布或示例菜单价格，未计算税费或餐卡折扣。未发送至餐厅。"],
"Listed menu prices only. Nothing was sent to a dining location.":["Solo precios del menú. No se envió nada al local.", "仅菜单标价。未发送至餐厅。"],
"Finish or cancel the current input before reviewing or confirming.":["Termina o cancela la entrada antes de revisar o confirmar.", "请完成或取消当前输入后再核对或确认。"],
"That option is not available for that item. Your cart was not changed.":["Esa opción no está disponible para ese artículo. Tu pedido no cambió.", "该餐品不支持此选项。订单未更改。"],
"That edit did not match the order format. Your cart was not changed.":["No se pudo validar ese cambio. Tu pedido no cambió.", "无法验证此修改。订单未更改。"],
"An order can hold 5 lines and 10 total items.":["Un pedido admite 5 líneas y 10 unidades en total.", "订单最多 5 行，共 10 件。"],
"There are no earlier cart edits to restore.":["No hay cambios anteriores que deshacer.", "没有可撤销的修改。"],
"That choice is no longer active.":["Esa opción ya no está activa.", "该选择已失效。"],
"This simulated order is complete. Start a new order to edit.":["Este pedido simulado está completo. Empieza otro pedido para editar.", "模拟订单已完成。请开始新订单。"],
"Local rules selected. Typed ordering works without internet.":["Reglas locales: solo pedidos sencillos en inglés. También puedes usar el menú sin conexión.", "已选本地规则，仅支持简单英语。也可离线使用菜单按钮。"],
"Understanding is unavailable. Choose Local only for simple typed orders, or use the menu.":["No se pudo interpretar el pedido. Usa los botones del menú o las reglas locales en inglés.", "暂时无法理解点单。请使用菜单按钮或本地英语规则。"],
"e.g. extra ice":["p. ej. hielo extra", "例如：多加冰"],
"Ticket":["Recibo", "票据"],
"Estimated preparation wait:":["Espera estimada de preparación:", "预计备餐等待："],
"unavailable":["no disponible", "暂无数据"],
"Simulated wait times":["Tiempos de espera simulados", "模拟等待时间"],
"The complete estimate is unavailable because at least one item’s wait is unknown.":["No hay una estimación completa porque se desconoce la espera de al menos un artículo.", "至少一件餐品的等待时间未知，无法给出完整估计。"],
"Uses the maximum vendor wait, assuming parallel preparation. Excludes walking and pickup travel.":["Usa la espera máxima del local, suponiendo preparación simultánea. No incluye desplazamientos.", "假設備餐同时进行，取餐厅等待时间的最大值，不含步行和取餐路程。"],
"· last mentioned":["· último mencionado", "· 上次提到"],
"Parser connection enabled. Local rules remain available if the server is unavailable.":["Conexión activada. Las reglas locales en inglés siguen disponibles si falla el servidor.", "已启用在线解析。服务器不可用时仍可使用本地英语规则。"],
"Transcribing with Gemini…":["Transcribiendo con Gemini…","Gemini 正在转写…"],
"Gemini transcribes your microphone recording. Internet required. Keep it under 30 seconds.":["Gemini transcribe tu grabación. Requiere internet. Máximo 30 segundos.","Gemini 将转写您的录音。需要联网，请在 30 秒内说完。"],
"Gemini could not transcribe this recording. Please type your order or try again.":["Gemini no pudo transcribir la grabación. Escribe tu pedido o inténtalo de nuevo.","Gemini 未能转写此录音。请打字点单或重试。"],
"Please keep recordings under 30 seconds. Nothing was submitted.":["Graba menos de 30 segundos. No se envió ningún pedido.","请将录音控制在 30 秒内。未提交任何点单。"],
'Language':['Idioma','语言'], 'Menu':['Menú','菜单'], 'Review':['Revisar','确认内容'], 'Receipt':['Recibo','收据'],
'Ready':['Listo','就绪'], 'Listening':['Escuchando','正在聆听'], 'Processing':['Procesando','正在处理'], 'Responding':['Respondiendo','正在回复'],
'Read replies aloud':['Leer respuestas en voz alta','朗读回复'], 'Talk':['Hablar','开始说话'], 'Stop — I’m done':['Parar — terminé','停止 — 我说完了'],
'Type your order':['Escribe tu pedido','输入您的点单内容'], 'Submit':['Enviar','提交'], 'Discard':['Descartar','放弃输入'], 'Cancel':['Cancelar','取消'], 'Listening…':['Escuchando…','正在聆听…'],
'say your order':['di tu pedido','请说出您的点单内容'], 'starting mic…':['iniciando micrófono…','正在启动麦克风…'], 'Heard:':['Escuchado:','识别内容：'], 'Working on:':['Procesando:','正在处理：'],
'Press the mic and speak, or type a request and press Submit.':['Pulsa el micrófono y habla, o escribe tu pedido y pulsa Enviar.','点击麦克风说话，或输入内容后点击提交。'],
'Say or type your order':['Di o escribe tu pedido','请说出或输入您的点单内容'],
'Voice isn’t available in this browser — typing works the same.':['Este navegador no admite voz; puedes escribir tu pedido.','此浏览器不支持语音，您仍可输入点单。'],
'All items':['Todos los artículos','全部'], 'Mains':['Platos principales','主食'], 'Sides':['Acompañamientos','配菜'], 'Drinks':['Bebidas','饮料'], 'Main':['Principal','主食'], 'Side':['Acompañamiento','配菜'], 'Drink':['Bebida','饮料'],
'On the menu':['En el menú','菜单'], 'Find an item':['Buscar un artículo','查找餐品'], 'Search this menu':['Buscar en este menú','搜索此菜单'],
'Your order':['Tu pedido','您的订单'], 'Your order is empty.':['Tu pedido está vacío.','您的订单为空。'], 'Tap an item, type an order, or press the mic and say one.':['Elige un artículo, escribe o usa el micrófono.','选择餐品、输入内容，或点击麦克风点单。'],
'Items':['Artículos','数量'], 'Tax and fees':['Impuestos y cargos','税费'], 'not calculated':['no calculados','未计算'], 'Menu subtotal':['Subtotal del menú','菜单小计'], 'Total':['Total','合计'], 'Order total':['Total del pedido','订单合计'],
'Undo':['Deshacer','撤销'], 'Clear':['Vaciar','清空'], 'Review order':['Revisar pedido','核对订单'], 'Check your order':['Revisa tu pedido','请核对您的订单'], 'Read it back':['Leer el pedido','朗读订单'],
'Confirm simulated order':['Confirmar pedido simulado','确认模拟订单'], 'Talking or editing again cancels this review.':['Hablar o editar de nuevo cancela esta revisión.','再次说话或编辑会使本次核对失效。'],
'New order':['Nuevo pedido','新订单'], 'Start a new order':['Empezar otro pedido','开始新订单'], 'Simulated receipt':['Recibo simulado','模拟收据'], 'No purchase or kitchen dispatch':['Sin compra ni envío a cocina','不会购买或发送至厨房'],
'Simulated · no real purchase':['Simulación · sin compra real','模拟演示 · 不会实际购买'], 'Order summary':['Resumen del pedido','订单明细'],
'Remove':['Eliminar','移除'], 'Add note':['Añadir nota','添加备注'], 'Edit note':['Editar nota','编辑备注'], 'Save note':['Guardar nota','保存备注'], 'Special request:':['Petición especial:','特殊要求：'],
'Request only. Extra charges are not included. Clear the text to remove this note.':['Solo es una petición. No incluye posibles cargos adicionales. Borra el texto para quitar la nota.','仅记录要求，不含可能产生的额外费用。清空文字并保存可移除备注。'],
'Special requests need counter confirmation. Availability and any extra charge are not confirmed.':['Las peticiones especiales requieren confirmación del local, incluida su disponibilidad y posibles cargos.','特殊要求及其可行性、额外费用需由柜台确认。'],
'Your food requirements':['Tus requisitos alimentarios','饮食要求'], 'For this order':['Para este pedido','用于本次订单'], 'For this cart':['Para este pedido','本订单的要求'], 'Edit requirements':['Editar requisitos','修改要求'],
'Preferences, allergies and dislikes stay separate. Changing them rechecks your cart; it does not silently remove food.':['Las preferencias, alergias y alimentos que evitas se guardan por separado. Al cambiarlos se revisa el pedido sin eliminar comida automáticamente.','偏好、过敏和不喜欢的食材分别保存。修改后会重新检查订单，不会自动删除餐品。'],
'Dietary preference':['Preferencia alimentaria','饮食偏好'], 'No dietary preference':['Sin preferencia','无偏好'], 'Vegetarian':['Vegetariano','素食'], 'Vegan':['Vegano','纯素'],
'Food allergy':['Alergia alimentaria','食物过敏'], 'Add allergy':['Añadir alergia','添加过敏原'], 'Disliked ingredient':['Ingrediente que evitas','不喜欢的食材'], 'Add dislike':['Añadir ingrediente','添加忌口食材'],
'Build my meal':['Crear mi comida','搭配套餐'], 'Optional · choose required parts and a budget':['Opcional · elige componentes y presupuesto','可选 · 选择组成和预算'], 'Maximum menu subtotal ($)':['Subtotal máximo del menú ($)','菜单小计上限（美元）'],
'Apply budget':['Aplicar presupuesto','应用预算'], 'Required meal parts':['Componentes requeridos','套餐组成'], 'Lock item':['Fijar artículo','锁定餐品'], 'Unlock':['Desbloquear','解除锁定'],
'Your choice':['Tu elección','请选择'], 'Proposed · not applied':['Propuesta · sin aplicar','建议方案 · 尚未应用'], 'These cart items need attention':['Estos artículos requieren atención','这些餐品需要注意'],
'Which one?':['¿Cuál?','您指的是哪一个？'], 'A quick question':['Una pregunta','请确认一下'],
'Order from':['Pedir en','点餐地点'], 'Demo Counter':['Mostrador de demostración','演示柜台'], 'Seeded menu · sample prices':['Menú de ejemplo · precios ilustrativos','示例菜单 · 示例价格'],
'View source menu':['Ver menú original','查看原菜单'], 'CMU location details':['Detalles del local CMU','CMU 餐厅信息'],
'Burger':['Hamburguesa','汉堡'], 'Chicken Sandwich':['Sándwich de pollo','鸡肉三明治'], 'Veggie Wrap':['Wrap vegetal','蔬菜卷'], 'Grilled Cheese':['Sándwich de queso','烤芝士三明治'], 'Fries':['Papas fritas','薯条'], 'Onion Rings':['Aros de cebolla','洋葱圈'], 'Side Salad':['Ensalada','配菜沙拉'], 'Lemonade':['Limonada','柠檬水'], 'Iced Tea':['Té helado','冰茶'], 'Cola':['Refresco de cola','可乐'], 'Water':['Agua','水'],
'Double':['Doble','双层肉饼'], 'Extra cheese':['Queso extra','加芝士'], 'No onions':['Sin cebolla','不要洋葱'], 'No lettuce':['Sin lechuga','不要生菜'], 'No mayo':['Sin mayonesa','不要蛋黄酱'], 'No ice':['Sin hielo','不要冰'], 'Dressing on side':['Aderezo aparte','酱汁另放'],
'What sounds good? Say or type your order, or tap an item.':['¿Qué te apetece? Di o escribe tu pedido, o elige un artículo.','想吃什么？您可以说话、打字或选择餐品。'],
'Anything else? Say another item, or review your order.':['¿Algo más? Pide otro artículo o revisa tu pedido.','还需要什么吗？继续点餐或核对订单。'],
'Your simulated receipt is ready. Nothing was purchased or sent to a dining location.':['Tu recibo simulado está listo. No se compró ni se envió nada al local.','模拟收据已生成。未实际购买，也未发送至餐厅。'],
'Choose a quantity from 1 to 5.':['Elige una cantidad de 1 a 5.','数量请选择 1 至 5。'], 'Review the current order before confirming it.':['Revisa el pedido actual antes de confirmarlo.','请先核对当前订单，再确认。'], 'Add something to your cart first.':['Añade un artículo primero.','请先添加餐品。'],
'That item is not in your cart. Select a cart row or add it first.':['Ese artículo no está en tu pedido. Selecciona una fila o añádelo primero.','订单中没有该餐品。请选择已有餐品或先添加。'],
'Choose the cart item you meant.':['Elige el artículo al que te refieres.','请选择您指的餐品。'],
'Language changed. Review your order again before confirming.':['Idioma cambiado. Revisa de nuevo antes de confirmar.','语言已切换。确认前请重新核对订单。'],
'Local rules understand simple English orders. Use the menu buttons offline.':['Las reglas locales entienden pedidos sencillos en inglés. Sin conexión, usa los botones del menú.','本地规则仅支持简单英语。离线时请使用菜单按钮。'],
'Speech support depends on your browser and installed voices. You can always type.':['La voz depende del navegador y de las voces instaladas. Siempre puedes escribir.','语音支持取决于浏览器和已安装的语音，您也可以直接输入。'],
'No matching readback voice is installed. Read the review on screen.':['No hay una voz instalada para este idioma. Lee el pedido en pantalla.','未安装此语言的朗读语音，请查看屏幕上的订单。'],
'Menu names and detailed source information stay as published.':['Los nombres del menú y la información detallada conservan su idioma original.','餐品名称和详细来源信息保留原文。'],
'Added':['Añadido','已添加'], 'Updated':['Actualizado','已更新'], 'Removed':['Eliminado','已移除'], 'Order updated.':['Pedido actualizado.','订单已更新。'], 'Please check the details below.':['Revisa los detalles a continuación.','请查看下方详细信息。'],
};
export function translate(text: string, language: Language = 'en-US'): string {
  if(language==='en-US')return text;
  const trimmed=text.trim();const match=messages[trimmed] ?? Object.entries(messages).find(([key])=>key.toLowerCase()===trimmed.toLowerCase())?.[1];
  if(match)return text.replace(trimmed,match[language==='es-ES'?0:1]);
  const question=trimmed.match(/^Which (.+) line did you mean\?$/);
  if(question){const name=translate(question[1],language);return language==='es-ES'?`¿Qué línea de ${name} querías?`:`您指的是哪一份${name}？`;}
  const line=trimmed.match(/^(.+) (\d+), quantity (\d+)(.*)$/);
  if(line)return language==='es-ES'?`${translate(line[1],language)} ${line[2]}, cantidad ${line[3]}${line[4]}`:`${translate(line[1],language)} ${line[2]}，数量 ${line[3]}${line[4]}`;
  return text;
}
